sudo: required
services: 
  - docker

before_install:
  - docker build -t dockermaryam/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockermaryam/react-test npm test -- --coverage

after_success:
  - docker build -t dockermaryam/multi-client ./client
  - docker build -t dockermaryam/multi-nginx ./nginx
  - docker build -t dockermaryam/multi-server ./server
  - docker build -t dockermaryam/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

  # Take those images and push them to Docker Hub
  - docker push dockermaryam/multi-client
  - docker push dockermaryam/multi-nginx
  - docker push dockermaryam/multi-server
  - docker push dockermaryam/multi-worker